project:
  type: website
  output-dir: docs

website:
  title: "Homework 2: PCA for Image Compression"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: appdesign.qmd
        text: App Design

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

